version: "3.4"
services:
  app:
    image: registry.gitlab.bzcom.vn/bzcom-uda/uda-be:latest
    ports:
      - "8084:8080"
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5